config/routes.rb
Rails.application.routes.draw do
  get 'store', to: 'store#index', as: 'store_index' # Página principal de la tienda
  get 'store/:id', to: 'store#show', as: 'store_product' # Página de detalles del producto

  root 'pages#home'
  devise_for :users

  authenticate :seller_user do
    root to: 'seller#home', as: :seller_root
  end

  namespace :seller, path: '', as: '' do
    resources :products
    resources :stocks
    resources :orders
  end

  get "up" => "rails/health#show", as: :rails_health_check

  get "seller" => "seller#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: [:pending , :processed , :shipped , :delivered , :cancelled]
  has_many :order_products, dependent: :destroy
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model

  belongs_to  :category
  has_many_attached :images
  has_many :stocks, dependent: :destroy
  has_many :order_products, dependent: :destroy
  belongs_to :user

  enum status: [:pending_review, :published, :rejected, :approved]

  pg_search_scope :search_full_text, against: {
    title: 'A',
    description: 'B',
  }

  ORDER_BY = {
    newest: "created_at DESC",
    expensive: "price DESC",
    cheaper: "price ASC"
  }

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, :numericality => { greater_than_or_equal_to: 0 }
  validates :category_id, presence: true

end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product

  validates :quantity, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, dependent: :destroy

  enum role: [:customer, :seller]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pagy::Backend

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @products = Product.all
  end
end

app/controllers/seller/orders_controller.rb
class Seller::OrdersController < SellerController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /sellers/orders or /sellers/orders.json
  def index
    @orders = Order.all
  end

  # GET /sellers/orders/1 or /sellers/orders/1.json
  def show
  end

  # GET /sellers/orders/new
  def new
    @order = Order.new
  end

  # GET /sellers/orders/1/edit
  def edit
  end

  # POST /sellers/orders or /sellers/orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/orders/1 or /sellers/orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/orders/1 or /sellers/orders/1.json
  def destroy
    @order.destroy!

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:customer_email, :product_quantity, :total_price, :status, :shipping_address, :customer_name, :customer_phone)
    end
end

app/controllers/seller_controller.rb
class SellerController < ApplicationController
  before_action :authenticate_user!
  layout 'seller'
  def home
  end


end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pagy_helper.rb
# app/helpers/pagy_helper.rb
module PagyHelper
  include Pagy::Frontend

  def pagy_custom_nav(pagy)
    pagy_nav_html = pagy_nav(pagy)

    # Reemplaza las clases por defecto de Pagy con clases de Tailwind
    pagy_nav_html.gsub!('class="', 'class="flex justify-center items-center space-x-2 my-4 bg-blue-200 ') # Agregar clases a la lista
    pagy_nav_html.gsub!('class="pagy-selected"', 'class="bg-blue-600 text-white px-4 py-2 rounded-lg shadow-md"') # Estilo para el elemento seleccionado
    pagy_nav_html.gsub!('class="pagy-disabled"', 'class="opacity-50 cursor-not-allowed"') # Estilo para los elementos deshabilitados

    pagy_nav_html
  end
end

app/helpers/seller_helper.rb
module SellerHelper
  def enum_l(record, enum_name)
    I18n.t("activerecord.attributes.#{record.class.name.underscore}.#{enum_name.to_s.pluralize}.#{record.send(enum_name)}")
  end
end

app/helpers/sellers/orders_helper.rb
module Sellers::OrdersHelper
end

app/helpers/sellers/products_helper.rb
module Sellers::ProductsHelper
end

app/helpers/sellers/stocks_helper.rb
module Sellers::StocksHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsEcomm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <script src="https://cdn.tailwindcss.com"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <main class="">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/seller.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('app_name') %> | <%= t('meta_title') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <script src="https://cdn.tailwindcss.com"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <main class="flex w-full">
    <%= render 'shared/header_seller' %>
    <%= render 'shared/flash' %>
    <div class="w-full">
      <%= render 'shared/navbar' %>
      <%= yield %>
    </div>
  </main>
  </body>
</html>

app/views/pages/home.html.erb
<p>Home Page</p>

app/views/shared/_dropdown_menu.html.erb
<!-- Main modal -->
<div id="timeline-modal" tabindex="-1" aria-hidden="true" class="">
  <div>
    <!-- Modal content -->
    <div>
      <!-- Modal body -->
      <div class="p-5">
        <ol class="relative border-s-2 border-indigo-500 dark:border-indigo-600 ms-3.5 h-32 mb-3">
          <li class="mb-10 ms-5">
            <span class="absolute flex items-center justify-center w-3 h-3 bg-gray-100 rounded-full -start-1.5 ring-2 ring-white  dark:bg-indigo-600">
              <%#= icon('fa-solid', 'warehouse', class: 'bg-white') %>
            </span>
            <%= link_to products_path, class: 'flex items-start text-sm font-semibold text-gray-700', role: 'menuitem', tabindex: '-1', id: 'menu-item-0' do %>
              <span>Inventory</span>
            <% end %>
          </li>
          <li class="mb-10 ms-5">
            <span class="absolute flex items-center justify-center w-3 h-3 bg-gray-100 rounded-full -start-1.5 ring-2 ring-white  dark:bg-indigo-600">
              <%#= icon('fa-solid', 'circle-plus', class: 'bg-white') %>
            </span>
            <%= link_to new_product_path, class: 'flex items-start text-sm font-semibold text-gray-700', role: 'menuitem', tabindex: '-1', id: 'menu-item-0' do %>
              <span>Create product</span>
            <% end %>
          </li>
          <li class="ms-5">
            <span class="absolute flex items-center justify-center w-3 h-3 bg-gray-100 rounded-full -start-1.5 ring-2 ring-white  dark:bg-indigo-600">
              <%#= icon('fa-solid', 'cubes', class: 'bg-white') %>
            </span>
            <%= link_to stocks_path, class: 'flex justify-start text-sm font-semibold text-gray-700', role: 'menuitem', tabindex: '-1', id: 'menu-item-0' do %>
              <span>Stocks</span>
            <% end %>
          </li>
        </ol>
      </div>
    </div>
  </div>
</div>

<!-- _dropdown_menu.html.erb -->
<!--<div class="py-1">-->
  <%#= link_to products_path, class: 'text-gray-700 block px-4 py-2 text-sm hover:rounded hover:bg-gray-200', role: 'menuitem', tabindex: '-1', id: 'menu-item-0' do %>
<!--    <span>Inventory</span>-->
  <%# end %>
  <%#= link_to new_product_path, class: 'text-gray-700 block px-4 py-2 text-sm hover:rounded hover:bg-gray-200', role: 'menuitem', tabindex: '-1', id: 'menu-item-0' do %>
<!--    <span>Create product</span>-->
  <%# end %>
  <%#= link_to stocks_path, class: 'text-gray-700 block px-4 py-2 text-sm hover:rounded hover:bg-gray-200', role: 'menuitem', tabindex: '-1', id: 'menu-item-0' do %>
<!--    <span>Stocks</span>-->
  <%# end %>
<!--</div>-->

app/views/shared/_flash.html.erb
<% if alert || notice %>
  <% color = alert ? 'bg-red-400' : 'bg-green-400' %>
  <div class="fixed top-0 inset-x-0 m-4 z-30 pointer-events-none">
    <div class="flex flex-col items-end space-y-4">
      <div data-controller="alert" data-alert-target="flash" class="ease-in-out duration-500 max-w-sm w-full shadow-lg rounded px-4 py-3 relative <%= color %> text-white pointer-events-auto transform transition-all opacity-100">
        <div class="p-2">
          <div class="flex items-start">
            <div class="ml-3 w-0 flex-1 pt-0.5">
              <p class="text-sm leading-5 font-medium">
                <%= alert || notice %>
              </p>
            </div>
            <div class="ml-4 flex-shrink-0 flex">
              <button data-action="click->alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_header_seller.html.erb
<nav class="w-64 p-4 h-screen bg-white sticky top-0 border border-gray-200 shadow-lg">
  <div class="flex">
    <%# <%= image_tag 'logo.png', class: "w-16" %>
    <h1 class="text-2xl py-2 text-black font-bold hidden md:block">Ecomm Admin</h1>
  </div>
  <ul>
    <li>
      <!-- Dropdown Menu -->
      <div data-controller="dropdown">
        <button type="button" class="w-full text-left block px-4 py-2 text-gray-500 hover:rounded hover:bg-gray-200 text-sm" data-action="click->dropdown#toggle">
          <%= icon('fa-solid', 'bars', class: 'mr-2') %>
          <span class="hidden md:inline-block"><%= t('header_admin.products') %></span>
          <%= icon('fa-solid', 'caret-down', class: 'ms-8') %>
        </button>
        <div data-dropdown-target="menu" class="hidden">
          <%= render partial: 'shared/dropdown_menu' %>
        </div>
      </div>
    </li>
    <li>
      <%= link_to seller_path, class: "block px-4 py-2 text-gray-500 hover:rounded hover:bg-gray-200 text-sm" do %>
        <%= icon('fa-solid', 'table-columns', class: 'mr-2') %> <span class="hidden md:inline-block"><%= t('header_admin.dashboard') %></span>
      <% end %>
    </li>
    <li>
      <%= link_to orders_path, class: "block px-4 py-2 text-gray-500 hover:rounded hover:bg-gray-200 text-sm" do %>
        <%= icon('fa-solid', 'truck-fast', class: 'mr-2 ') %> <span class="hidden md:inline-block"><%= t('header_admin.orders') %></span>
      <% end %>
    </li>
    <li>
      <%= link_to destroy_user_session_path, data: { "turbo-method": :delete, "turbo-confirm": "Are you sure you want to sign out?" }, class: "block px-4 py-2 text-gray-500 hover:rounded hover:bg-gray-200 text-sm" do %>
        <%= icon('fa-solid', 'sign-out', class: 'mr-2 ') %> <span class="hidden md:inline-block">Sign out</span>
      <% end %>
    </li>
  </ul>

</nav>

app/views/shared/_items.html.erb
<% if user_signed_in? %>

  <%#= link_to 'Add product', root_path, class: "mx-2 text-red-500 font-bold", data: { turbo_frame: 'modal' } %>
  <%#= link_to 'Favorites', root_path, class: "mx-2 text-red-500 font-bold" %>
  <%#= link_to 'Categories', root_path, class: "mx-2 text-red-500 font-bold" %>
  <%#= link_to 'Login', root_path, class: "mx-2 text-sky-900 font-bold" %>
  <button class="mx-2 text-sky-900 font-bold">
    <%= icon('fa-regular', 'bell') %>
  </button>
  <button class="mx-2 text-sky-900 font-bold">
    <%= icon('fa-regular', 'moon') %>
  </button>
  <%= image_tag "https://via.placeholder.com/40", alt: "Profile Image", class: "rounded-full h-10 w-10 mx-2" %>


<% end %>

app/views/shared/_navbar.html.erb
<nav class="bg-white border border-gray-200 shadow-sm">
  <div class="container mx-auto px-4 flex justify-between items-center">
    <%= link_to products_path, class: "text-2xl font-bold text-sky-900" do %>
      <%= current_user.full_name %>
    <% end %>

    <button data-action="click->menu#toggle" class="sm:hidden">
      <%= icon('fa-solid', 'list') %>
    </button>

    <div class="hidden sm:flex space-x-4">
      <%= render partial: 'shared/items' %>
    </div>

    <div data-menu-target="items" class="sm:hidden fixed top-0 right-0 w-3/5 bg-white shadow z-10 h-full flex flex-col transform translate-x-full transition duration-200 ease-in-out">
      <button data-action="click->menu#toggle">
        <%= icon('fa-solid', 'x') %>
      </button>
      <%= render partial: 'shared/items' %>
    </div>
  </div>
</nav>