config/routes.rb
Rails.application.routes.draw do
  get 'store', to: 'store#index', as: 'store_index' # Página principal de la tienda
  get 'store/:id', to: 'store#show', as: 'store_product' # Página de detalles del producto

  root 'pages#home'
  devise_for :users

  authenticate :seller_user do
    root to: 'seller#home', as: :seller_root
  end

  namespace :seller, path: '', as: '' do
    resources :products
    resources :stocks
    resources :orders
  end

  get "up" => "rails/health#show", as: :rails_health_check

  get "seller" => "seller#home"

end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product

  validates :quantity, numericality: { greater_than: 0 }
end

app/controllers/seller/orders_controller.rb
class Seller::OrdersController < SellerController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /sellers/orders or /sellers/orders.json
  def index
    @orders = Order.all
  end

  # GET /sellers/orders/1 or /sellers/orders/1.json
  def show
  end

  # GET /sellers/orders/new
  def new
    @order = Order.new
  end

  # GET /sellers/orders/1/edit
  def edit
  end

  # POST /sellers/orders or /sellers/orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/orders/1 or /sellers/orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/orders/1 or /sellers/orders/1.json
  def destroy
    @order.destroy!

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:customer_email, :product_quantity, :total_price, :status, :shipping_address, :customer_name, :customer_phone)
    end
end

app/controllers/seller/products_controller.rb
class Seller::ProductsController < SellerController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /seller/products or /seller/products.json
  def index
    @pagy, @products = pagy(FindProductsSellers.new(current_user).call_params(products_params_index))

    # if params[:category_id]
    #   @products = @products.where(category_id: params[:category_id])
    # end
    #
    # if params[:min_price].present?
    #   @products = @products.where("price >= ?", params[:min_price])
    # end
    #
    # if params[:max_price].present?
    #   @products = @products.where("price <= ?", params[:max_price])
    # end
    #
    # if params[:query_text].present?
    #   @products = @products.search_full_text(params[:query_text])
    # end
    #
    # # We check if the parameter exists with &
    # orders = Product::ORDER_BY.fetch(params[:order_by]&.to_sym, Product::ORDER_BY[:newest])
    #
    # @products = @products.order(orders)
  end

  # GET /seller/products/1 or /seller/products/1.json
  def show
  end

  # GET /seller/products/new
  def new
    @product = Product.new
  end

  # GET /seller/products/1/edit
  def edit
  end

  # POST /seller/products or /seller/products.json
  def create
    # @product = Product.new(product_params)
    @product = current_user.products.new(product_params)
    if @product.save
      redirect_to product_url(@product), notice: "Product was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /seller/products/1 or /seller/products/1.json
  def update
    @product = Product.find(params[:id])
    if @product.update(product_params.reject { |k| k["images"] })
      if product_params[:images]
        product_params[:images].each do |image|
          @product.images.attach(image)
        end
      end
      redirect_to product_url(@product), notice: "Product was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /seller/products/1 or /seller/products/1.json
  def destroy
    @product.destroy!
    redirect_to products_url, notice: "Product was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:title, :description, :price, :category_id, images: [])
  end

  def products_params_index
    params.permit(:category_id, :min_price, :max_price, :query_text, :order_by)
  end
end

app/controllers/seller/stocks_controller.rb
class Seller::StocksController < SellerController
  before_action :set_stock, only: %i[ show edit update destroy ]

  # GET /sellers/stocks or /sellers/stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /sellers/stocks/1 or /sellers/stocks/1.json
  def show
  end

  # GET /sellers/stocks/new
  # inicializa el nuevo stock con el product_id que se pasa en los parámetros:
  def new
    if params[:product_id].present?
      @stock = Stock.new(product_id: params[:product_id])
    else
      @stock = Stock.new
    end
  end

  # GET /sellers/stocks/1/edit
  def edit
  end

  # POST /sellers/stocks or /sellers/stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/stocks/1 or /sellers/stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/stocks/1 or /sellers/stocks/1.json
  def destroy
    @stock.destroy!

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:quantity, :product_id)
    end
end

app/controllers/seller_controller.rb
class SellerController < ApplicationController
  before_action :authenticate_user!
  layout 'seller'
  def home
  end


end

app/helpers/seller_helper.rb
module SellerHelper
  def enum_l(record, enum_name)
    I18n.t("activerecord.attributes.#{record.class.name.underscore}.#{enum_name.to_s.pluralize}.#{record.send(enum_name)}")
  end
end

app/helpers/sellers/orders_helper.rb
module Sellers::OrdersHelper
end

app/helpers/sellers/products_helper.rb
module Sellers::ProductsHelper
end

app/helpers/sellers/stocks_helper.rb
module Sellers::StocksHelper
end

app/views/seller/stocks/_form.html.erb
<div class="max-w-2xl bg-white shadow-md rounded-lg border px-8 pt-6 pb-8 mb-4">
  <%= form_with(model: stock, class: "contents") do |form| %>

    <% if stock.errors.any? %>
      <div id="error_explanation" class="bg-red-100 text-red-700 px-3 py-2 font-medium rounded-lg mt-3 border border-red-400">
        <h2><%= t('activerecord.errors.models.stock.save_error') %></h2>

        <ul>
          <% stock.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="relative z-0 w-full my-5 group">
      <%= form.text_field :quantity, id: 'floating_quantity', class: "block py-2.5 px-0 w-full text-sm text-black bg-transparent border-0 border-b border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer", placeholder: " " %>
      <%= form.label :quantity, t('forms.stocks.quantity'), for: 'floating_title', class: "peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
    </div>

    <% if stock.product_id.nil? %>
      <div class="relative z-0 w-full my-10 group">
        <%= form.collection_select :product_id, current_user.products, :id, :title, { prompt: " " }, { id: 'floating_category_id', class: "block py-2.5 px-0 w-full text-sm text-black bg-transparent border-0 border-b border-gray-300 appearance-none dark:text-black dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" } %>
        <%= form.label :product_id, t('forms.stocks.products'), for: 'floating_category_id', class: "peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6" %>
      </div>
    <% else %>
      <%= form.hidden_field :product_id %>
    <% end %>

    <div class="inline">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-indigo-500 text-white inline-block font-medium cursor-pointer hover:bg-indigo-700 focus:outline-none focus:ring-0 focus:ring-blue-500 focus:ring-offset-2" %>
      <%= link_to "Back to stocks", stocks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    </div>
  <% end %>

</div>

app/views/seller/stocks/_stock.html.erb
<tr class="bg-white border-b  hover:bg-gray-200">
  <td class="w-4 p-4">
    <div class="flex items-center">
      <input id="checkbox-table-search-<%= stock.id %>" type="checkbox" class="w-4 h-4 text-blue-600 bg-white rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-white focus:ring-2  dark:border-gray-600">
      <label for="checkbox-table-search-<%= stock.id %>" class="sr-only">checkbox</label>
    </div>
  </td>
  <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-black">
    <%= stock.product.title %>
  </th>
  <td class="px-10 py-4 text-black">
    <%= stock.quantity %>
  </td>
  <td class="px-6 py-4 text-black">
    <%= link_to "View", product_path(stock.product), class: "rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
  </td>
</tr>

app/views/seller/stocks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing stock</h1>

  <%= render "form", stock: @stock %>

  <%= link_to "Show this stock", @stock, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to stocks", stocks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/seller/stocks/index.html.erb
<div class="w-full px-5 py-5">
  <% content_for :title, "Stocks" %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= t('views.stock.stocks') %></h1>
    <%= link_to "Create stock", new_stock_path, class: "text-center rounded-lg py-3 px-5 bg-indigo-600 inline-block font-medium text-white hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-gray-300 dark:focus:ring-gray-600" %>
  </div>

  <section class="mt-3 relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-white border dark:text-gray-400">
      <tr>
        <th scope="col" class="p-4">
          <div class="flex items-center">
            <input id="checkbox-all-search" type="checkbox" class="w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:border-gray-600">
            <label for="checkbox-all-search" class="sr-only">checkbox</label>
          </div>
        </th>
        <th scope="col" class="px-6 py-3">
          <%= t('views.stock.product') %>
        </th>
        <th scope="col" class="px-6 py-3">
          <%= t('views.stock.quantity') %>
        </th>
        <th scope="col" class="px-6 py-3">
          Action
        </th>
      </tr>
      </thead>
      <tbody>
      <% @stocks.each do |stock| %>
        <%= render partial: 'stock', locals: { stock: stock } %>
      <% end %>
      </tbody>
    </table>
  </section>
</div>

app/views/seller/stocks/new.html.erb
<div class="md:w-2/3 w-full ml-5">

  <h1 class="font-bold text-4xl mb-3">New stock</h1>

  <%= render "form", stock: @stock %>

</div>

app/views/seller/stocks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @stock %>
    <%= link_to "Edit this stock", edit_stock_path(@stock), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to stocks", stocks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this stock", @stock, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>